name       : python-protobuf
version    : 3.11.3
release    : 12
source     :
    - https://github.com/protocolbuffers/protobuf/archive/v3.11.3.tar.gz : cf754718b0aa945b00550ed7962ddc167167bd922b842199eeb6505e6f344852
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Python bindings for Protobuf
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - protobuf
build      : |
    pushd python
    # Python macros were shitting themselves
    python2 setup.py build --cpp_implementation
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python2 setup.py install --root="%installroot%" --cpp_implementation
    python3 setup.py install --root="%installroot%" --cpp_implementation
