name       : python-protobuf
version    : 3.4.0
release    : 5
source     :
    - https://pypi.python.org/packages/89/45/3214bb758646a1a30459ca0f5b8f8164d6893f24725c58b632e663565f44/protobuf-3.4.0.tar.gz : ef02609ef445987976a3a26bff77119c518e0915c96661c3a3b17856d0ef6374
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Python bindings for Protobuf
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    # Fix derp
    chmod o+r -R %installroot%/usr/lib/python2.7/site-packages/protobuf-${version}-py2.7.egg-info
