name       : python-protobuf
version    : 3.6.1.3
release    : 11
source     :
    - https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz : 73fdad358857e120fd0fa19e071a96e15c0f23bb25f85d3f7009abfd4f264a2a
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Python bindings for Protobuf
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - protobuf
build      : |
    pushd python
    # Python macros were shitting themselves
    python2 setup.py build --cpp_implementation
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python2 setup.py install --root="%installroot%" --cpp_implementation
    python3 setup.py install --root="%installroot%" --cpp_implementation
