name       : python-protobuf
version    : 2.6.1
release    : 1
source     :
    - https://pypi.python.org/packages/source/p/protobuf/protobuf-2.6.1.tar.gz : 8faca1fb462ee1be58d00f5efb4ca4f64bde92187fe61fde32615bbee7b3e745
license    : BSD
homepage   : https://pypi.python.org/pypi/protobuf/2.6.1
summary    : python2 bindings for protobuf
description: |
    python2 bindings for protobuf
builddeps  :
    - pkgconfig(protobuf)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
