name       : python-protobuf
version    : 3.17.3
release    : 18
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.17.3.tar.gz : c6003e1d2e7fefa78a3039f19f383b4f3a61e81be8c19356f85b6461998ad3db
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Protocol Buffers are Google’s data interchange format.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
rundeps    :
    - protobuf
    - python-six
build      : |
    pushd python
    # Python macros do not work with this
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python3 setup.py install --root="%installroot%" --cpp_implementation
