name       : python-protobuf
version    : '21.12'
release    : 20
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v21.12.tar.gz : 22fdaf641b31655d4b2297f9981fa5203b2866f8332d3c6333f6b0107bb320de
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Protocol Buffers are Google’s data interchange format.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
rundeps    :
    - protobuf
    - python-six
build      : |
    pushd python
    # Python macros do not work with this
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python3 setup.py install --root="%installroot%" --cpp_implementation
