name       : python-protobuf
version    : 3.12.3
release    : 13
source     :
    - https://github.com/protocolbuffers/protobuf/archive/v3.12.3.tar.gz : 71030a04aedf9f612d2991c1c552317038c3c5a2b578ac4745267a45e7037c29
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Python bindings for Protobuf
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - protobuf
build      : |
    pushd python
    # Python macros do not work with this
    python2 setup.py build --cpp_implementation
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python2 setup.py install --root="%installroot%" --cpp_implementation
    python3 setup.py install --root="%installroot%" --cpp_implementation
