name       : python-protobuf
version    : 3.4.0
release    : 4
source     :
    - https://pypi.python.org/packages/89/45/3214bb758646a1a30459ca0f5b8f8164d6893f24725c58b632e663565f44/protobuf-3.4.0.tar.gz : ef02609ef445987976a3a26bff77119c518e0915c96661c3a3b17856d0ef6374
license    : BSD
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : python2 bindings for protobuf
description: |
    python2 bindings for protobuf
builddeps  :
    - pkgconfig(protobuf)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
    # Fix derp
    chmod o+r -R %installroot%/usr/lib/python2.7/site-packages/protobuf-${version}-py2.7.egg-info
